/*Apartado 1*/
DROP TABLE DEPARTSEQ;
CREATE TABLE DEPARTSEQ AS SELECT * FROM DEPART;

SELECT * 
FROM USER_TABLES
WHERE UPPER(TABLE_NAME)= 'DEPARTSEQ';

DESC DEPARTSEQ

SELECT * FROM DEPARTSEQ;

ALTER TABLE DEPARTSEQ
ADD CONSTRAINT ...;

/*Apartado 2*/
DROP SEQUENCE DEPT_ID_SEQ;

CREATE SEQUENCE DEPT_ID_SEQ
INCREMENT BY 10
START WITH 200
MAXVALUE 1000;

SELECT * FROM USER_SEQUENCES;

/*Apartado 3*/

SELECT sequence_name "NOMBRE DE SEQUENCIA", 
    max_value "VALOR MÁXIMO", 
    increment_by "INCREMENTO", 
    last_number "ÚLTIMO NÚMERO"
FROM USER_SEQUENCES
WHERE UPPER(SEQUENCE_NAME) = 'DEPT_ID_SEQ';
--Utlilizariamos all_secuences para ver todas

/*Apartado 4*/

--lab9_4.sql

/*Apartado 5*/

SELECT dept_id_seq.CURRVAL FROM dual;


/*Apartado 6*/

DROP TABLE CENTROS CASCADE CONSTRAINT;

CREATE TABLE CENTROS
(
ID NUMBER(2) GENERATED ALWAYS AS IDENTITY MINVALUE 10 MAXVALUE 90 INCREMENT BY 10 NOT NULL ENABLE,
NOMBRE VARCHAR(30) NOT NULL,
CALLE VARCHAR(30),
NUMERO NUMBER(2),
cp VARCHAR(5),
CIUDAD VARCHAR(15),
PROVINCIA VARCHAR(40),
TELEFONO VARCHAR(9),
CONSTRAINT CENTROS_ID_PK PRIMARY KEY (ID),
CONSTRAINT CENTROS_PROV_CK CHECK(PROVINCIA = UPPER(PROVINCIA)),
CONSTRAINT CENTROS_NUM_CK CHECK(NUMERO BETWEEN 0 AND 100)
);

DESC CENTROS

SELECT * FROM USER_CONSTRAINTS WHERE UPPER(TABLE_NAME)='CENTROS';

SELECT * FROM CENTROS;
/*Apartado 7*/

INSERT INTO CENTROS(nombre, calle, numero, cp, ciudad, provincia, telefono) VALUES('EGIBIDE', 'CALLE POZOA', 2, 01010, 'VITORIA', 'ALAVA', '945278415');
INSERT INTO CENTROS(nombre, calle, numero, cp, ciudad, provincia, telefono) VALUES('SAN VIATOR', 'CALLE SAN VIATOR', 24, 01009, 'VITORIA', 'ALAVA', '945220500');

SELECT * FROM CENTROS;

/*Apartado 8*/

CREATE INDEX DPTNEMPLE ON emple (dept_no);

select * from user_indexes;

select * from user_indexes 
where upper(index_name) = 'DPTNEMPLE';



/*Apartado 9*/

SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS FROM USER_INDEXES
WHERE upper(table_name)='EMPLE';

SELECT *
FROM USER_INDEXES E , USER_IND_COLUMNS D
WHERE E.INDEX_NAME=D.INDEX_NAME
AND upper(E.table_name)='EMPLE';

/*Apartado 10*/

DROP INDEX DPTNEMPLE;

select * from user_indexes;

select * from user_indexes 
where upper(index_name) = 'DPTNEMPLE';

/*Apartado 11*/

CREATE INDEX IND_DEPT_DNOMBRE ON departseq upper(dnombre);

DROP INDEX IND_DEPT_DNOMBRE;

/*Apartado 13*/

ALTER INDEX IND_DEPT_DNOMBRE MONITORING USAGE;

/*Apartado 14*/

SELECT * FROM v$object_usage;
--Usa
SELECT *
FROM departseq
WHERE dnombre='VENTAS';
--No usa
SELECT e.*
FROM emple e
WHERE upper(loc)= 'BARCELONA';

SELECT * FROM v$object_usage;

ALTER INDEX IND_DEPT_DNOMBRE NOMONITORING USAGE;


/*Apartado 15*/

CREATE PUBLIC SYNONYM DEP FOR DEPARTSEQ;

Desc DEP;
DROP PUBLIC SYNONYM DEP;

/*Apartado 16*/

SELECT * FROM ALL_SYNONYMS
WHERE upper(synonym_name)='DEP';

DROP PUBLIC SYNONYM DEP;

/*PRUEBAS VARIAS*/

CREATE PUBLIC SYNONYM "PRUEBASYSTEM"
FOR"SYSTEM"."EMPLE";

DROP PUBLIC SYNONYM PRUEBASYSTEM;

GRANT SELECT ON "SYSTEM"."EMPLE" TO "SCOTT";

SELECT * FROM ALL_TABLES
WHERE UPPER(TABLE_NAME)= 'EMPLE';

SELECT * FROM PRUEBASYSTEM;

SELECT * FROM ALL_SYNONYMS
WHERE UPPER(TABLE_OWNER) = 'SYSTEM';

