--1
DROP TRIGGER INS_EMPLE;

CREATE  OR REPLACE TRIGGER INS_EMPLE
BEFORE INSERT ON EMPLE
BEGIN
    IF (TO_CHAR(SYSDATE,'HH24:MI') NOT BETWEEN '09:50' AND '17:30') OR
       (TO_CHAR(SYSDATE,'DY') IN ('SAT', 'SUN')) THEN
       RAISE_APPLICATION_ERROR (-20001, 'SOLO SE PUEDE AÑADIR PERSONAL ENTRE LAS 9 Y LAS 17:30');
    END IF;
END;

INSERT INTO EMPLE VALUES (7934,'MUÑOZ','EMPLEADO',7782,'23/01/1982',169000,NULL,10);
INSERT INTO EMPLE VALUES (7934,'MUÑOZ','EMPLEADO',7782,'23/01/1982',169000,NULL,10);

ALTER TRIGGER INS_EMPLE DISABLE;

--2

CREATE OR REPLACE TRIGGER TRIGGER_CTRL_EMPLEADOS
AFTER INSERT OR DELETE OR UPDATE ON EMPLE
FOR EACH ROW
BEGIN
   CASE
       WHEN INSERTING  THEN 
           INSERT INTO CTRL_EMPLEADOS (TABLA, USUARIO, FECHA, OPER)
           VALUES('EMPLE', USER, SYSDATE, 'INSERT');
       WHEN UPDATING  THEN 
           INSERT INTO CTRL_EMPLEADOS (TABLA, USUARIO, FECHA, OPER)
           VALUES('EMPLE', USER, SYSDATE, 'UPDATE');
       WHEN DELETING THEN 
           INSERT INTO CTRL_EMPLEADOS (TABLA, USUARIO, FECHA, OPER)
           VALUES('EMPLEA', USER, SYSDATE, 'DELETE');
       ELSE
           RAISE_APPLICATION_ERROR(-20001, 'ERROR');
   END CASE;
END;


--3   
    
CREATE OR REPLACE TRIGGER DIS_EMPLEADOS_INSERTAR
BEFORE INSERT ON EMPLE
FOR EACH ROW
DECLARE
    V_NUM NUMBER(2);
BEGIN
    SELECT DEPT_NO INTO V_NUM FROM DEPART WHERE UPPER(DNOMBRE) = 'VENTAS';
    IF(:NEW.DEPT_NO = V_NUM) THEN
        RAISE_APPLICATION_ERROR(-20500, 'NO PUEDE INSERTAR EMPLEADOS EN EL DEPARTAMENTO "VENTAS" .');
    END IF;
END;


--4

CREATE OR REPLACE TRIGGER AUMENTOSALARIO
BEFORE UPDATE  OF SALARIO ON EMPLE
    FOR EACH ROW
    WHEN (NEW.SALARIO > OLD.SALARIO*1.20)
BEGIN
    RAISE_APPLICATION_ERROR
    (-20600,('AL EMPLE'||TO_CHAR(:NEW.EMP_NO)||
        'NO SE LE PUEDE AUMENTAR EL SALARIO MAS DE UN 20%'));
END;

--5

select * from user_views where view_name = 'EMPLEADODPTO';

CREATE OR REPLACE TRIGGER VALIDARVISTA
INSTEAD OF INSERT ON EMPLEADODPTO
FOR EACH ROW
DECLARE
    V_NUM NUMBER(10);
    LE$MAS_LOG EXCEPTION;
    PRAGMA EXCEPTION_INIT(LE$MAS_LOG, -6502);
    MAXIMO DEPART.DEPT_NO%TYPE;
BEGIN
    BEGIN
        SELECT DEPT_NO INTO V_NUM FROM DEPART WHERE DNOMBRE =:NEW.DNOMBRE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN        
            SELECT MAX(DEPT_NO) INTO MAXIMO FROM DEPART;
            INSERT INTO DEPART (DNOMBRE, DEPT_NO) VALUES (NEW.DNOMBRE, MAXIMO+10);
    END;
    
    IF(ENCONTRADO)THEN
    
        INSERT INTO EMPLE (EMP_NO, APELLIDO, DEPT_NO) VALUES (:NEW.EMP_NO, :NEW.APELLIDO, MAXIMO);
    
    ELSE
    
        INSERT INTO EMPLE (EMP_NO, APELLIDO, DEPT_NO, FECHA_ALTA) VALUES (:NEW.EMP_NO, :NEW.APELLIDO, V_NUM, SYSDATE);
    END IF;
END;
    
    
CREATE OR REPLACE TRIGGER InsertEmepleadoDpto 
INSTEAD OF INSERT ON EMPLEADODPTO 
DECLARE 
    v_cod DEPART.DEPT_NO%TYPE; 
BEGIN 
SELECT DNOMBRE
INTO v_cod 
FROM DEPART
WHERE DNOMBRE=:NEW.DNOMBRE; 
INSERT INTO Empleado 
VALUES INSERT INTO Departamento VALUES END;





