/*Ejercicio 1*/
SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER ins_productos
AFTER INSERT ON PRODUCTOS2
FOR EACH ROW
DECLARE

  l_coprod PRODUCTOS2.NO_PRODUCTO%TYPE;

BEGIN
  INSERT INTO PRODUCTOS2 (NO_PRODUCTO) VALUES (:NEW.NO_PRODUCTO);
  
  SELECT CO_PRODUCTO INTO l_coprod 
  FROM PRODUCTOS2
  WHERE NO_PRODUCTO = :NEW.NO_PRODUCTO;
  
  INSERT INTO PRECIOS_PRODUCTOS2 VALUES (l_coprod, 100, SYSDATE);
  
END ins_productos;

--Comprobar

/*SELECT PRODUCTOS2.CO_PRODUCTO, PRODUCTOS2.NO_PRODUCTO, PRECIOS_PRODUCTOS2.PRECIO, PRECIOS_PRODUCTOS2.FECHA_ACTUALIZACION
FROM PRODUCTOS2, PRECIOS_PRODUCTOS2
WHERE PRODUCTOS2.CO_PRODUCTO = PRECIOS_PRODUCTOS.CO_PRODUCTO;*/


/*Ejercicio 2*/

CREATE OR REPLACE TRIGGER insert_comision
BEFORE INSERT ON EMPLE FOR EACH ROW

BEGIN

  IF(:new.comision = 0)
  THEN 
      RAISE_APPLICATION_ERROR(-20100, 'LA COMISION NO PUEDE SER 0');
  END IF;
  
  IF(:new.comision = NULL)
  THEN
      RAISE_APPLICATION_ERROR(-20100, 'LA COMISION NO PUEDE SER NULA');
  END IF;
  
END;

INSERT INTO EMPLE VALUES (7777,'Rodrigo','EMPLEADO',7782,'23/01/1982',169000,0,10);
INSERT INTO EMPLE VALUES (7777,'Rodrigo','EMPLEADO',7782,'23/01/1982',169000,null,10);


/*Ejercicio 3*/

--Desabilitar el trigger

ALTER TRIGGER insert_comision DISABLE;


--Modificar el triger

CREATE OR REPLACE TRIGGER insert_comision
BEFORE INSERT ON EMPLE FOR EACH ROW

BEGIN

  IF(:new.comision = 0)
  THEN 
      INSERT INTO EMPLE VALUES (:new.EMP_NO, :new.APELLIDO, :new.OFICIO, :new.DIRECTOR, :new.FECHA_ALT, :new.SALARIO, 1, :new.DEPT_NO);
  END IF;
  
  IF(:new.comision = NULL)
  THEN
      RAISE_APPLICATION_ERROR(-20100, 'LA COMISION NO PUEDE SER NULA');
  END IF;
  
END;

--Habilitar el trigger

ALTER TRIGGER insert_comision ENABLE;

--Hacer una insert

INSERT INTO EMPLE VALUES (0000,'Rodrigo','EMPLEADO',7782,'23/01/1982',169000,0,10);