INSERT INTO DEPART (DEPT_NO, DNOMBRE) VALUES (50, 'INFORMATICA');
ROLLBACK;
SELECT * FROM DEPART;

UPDATE DEPART
SET LOC = 'CORDOBA'
WHERE DEPT_NO = 50;

SELECT * FROM DEPART;

UPDATE DEPART
SET LOC = 'ARAYA', DNOMBRE = 'EDUCACION'
WHERE DEPT_NO = 50;

UPDATE DEPART
SET LOC = NULL
WHERE DEPT_NO = 50;

DELETE FROM DEPART
WHERE DEPT_NO = 50;