--1
SELECT * FROM EMPLE;

SELECT APELLIDO, SALARIO, DEPT_NO
FROM EMPLE
WHERE SALARIO >= 200000
AND DEPT_NO IN (10, 20);

--2

SELECT APELLIDO 
FROM EMPLE
WHERE APELLIDO LIKE 'J%';

--3
SELECT APELLIDO
FROM EMPLE
WHERE APELLIDO LIKE '_R%';

--4
SELECT APELLIDO
FROM EMPLE
WHERE APELLIDO LIKE 'A%O%';

--5
SELECT APELLIDO, SALARIO
FROM EMPLE
WHERE SALARIO BETWEEN 150000 AND 200000;

--6
SELECT APELLIDO, SALARIO
FROM EMPLE
WHERE SALARIO NOT BETWEEN 150000 AND 200000;

--7
SELECT APELLIDO
FROM EMPLE
WHERE UPPER(OFICIO) IN ('VENDEDOR','ANALISTA','EMPLEADO');

--8
SELECT APELLIDO
FROM EMPLE
WHERE UPPER(OFICIO) NOT IN ('VENDEDOR','ANALISTA','EMPLEADO');
--9
SELECT APELLIDO
FROM EMPLE
WHERE DEPT_NO = 10 OR DEPT_NO = 30;

SELECT APELLIDO
FROM EMPLE
WHERE DEPT_NO IN (10, 30);

--10
SELECT APELLIDO
FROM EMPLE
WHERE DEPT_NO != 10 AND DEPT_NO != 30;

SELECT APELLIDO
FROM EMPLE
WHERE DEPT_NO NOT IN (10, 30);

--11
SELECT APELLIDO, COMISION_PCT
FROM EMPLE
WHERE COMISION_PCT IS NULL;

--12
SELECT APELLIDO, COMISION_PCT
FROM EMPLE
WHERE COMISION_PCT IS NOT NULL;

--13
SELECT APELLIDO, OFICIO
FROM EMPLE
WHERE ID_JEFE IS NULL;

--14
SELECT DISTINCT OFICIO 
FROM EMPLE;

--15
SELECT EMP_NO, APELLIDO, OFICIO, DEPT_NO 
FROM EMPLE
WHERE DEPT_NO IN 20
ORDER BY APELLIDO, SALARIO;

--16
SELECT APELLIDO, OFICIO
FROM EMPLE
WHERE UPPER (OFICIO) IN ('ANALISTA')
ORDER BY EMP_NO;