--4
/*Crea un script SQL que contenga lo necesario para la creación de las tablas Personas y Provincias.*/

DROP TABLE PERSONAS CASCADE CONSTRAINTS; 
DROP TABLE PROVINCIAS CASCADE CONSTRAINTS;

CREATE TABLE PROVINCIAS(
    COD_PROV NUMBER(2),
    NOM_PROV VARCHAR(15),
    CONSTRAINT COD_PRO_PK PRIMARY KEY(COD_PROV)
);

CREATE TABLE PERSONAS(
    DNI NUMBER(8),
    NOMBRE VARCHAR2(15),
    DIRECCION VARCHAR2(25),
    POBLACION VARCHAR2(20),
    COD_PROV NUMBER(2),
    CONSTRAINT DNI_PK PRIMARY KEY(DNI),
    CONSTRAINT COD_PROV_FK FOREIGN KEY (COD_PROV)
				REFERENCES PROVINCIAS(COD_PROV) ON DELETE CASCADE);
                
SELECT *
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME = 'PERSONAS';

SELECT *
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME = 'PROVINCIAS';

